-- --------------------------------------------------------
-- Date/time:                    2012-12-30 12:41:24
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping structure for table YAHOODATE.STOCK
DROP TABLE IF EXISTS `STOCK`;
CREATE TABLE IF NOT EXISTS `STOCK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `YAHOO_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table YAHOODATE.STOCK: ~173 rows (approximately)
/*!40000 ALTER TABLE `STOCK` DISABLE KEYS */;
INSERT INTO `STOCK` (`NAME`, `YAHOO_NAME`) VALUES
	('Accor Paris', 'AC.PA'),
	('Air Liquide', '419919.PA'),
	('Alcatel-Lucent', 'ALU.PA'),
	('Alstom', 'ALO.PA'),
	('ArcelorMittal', 'MT.PA'),
	('AXA', 'CS.PA'),
	('BNP Paribas', 'BNP.PA'),
	('Bouygues', 'EN.PA'),
	('Capgemini', 'CAP.PA'),
	('Carrefour', 'CA.PA'),
	('Crédit Agricole', 'ACA.PA'),
	('EADS', 'EAD.PA'),
	('EDF', 'EDF.PA'),
	('Essilor', 'EI.PA'),
	('France Télécom', 'FTE.PA'),
	('GDF Suez', 'GSZ.PA'),
	('Groupe Danone', 'BN.PA'),
	('L\'Oréal', 'OR.PA'),
	('Lafarge', 'LG.PA'),
	('Legrand', 'LR.PA'),
	('LVMH', 'MC.PA'),
	('Michelin', 'ML.PA'),
	('Pernod Ricard', 'RI.PA'),
	('PPR', 'PP.PA'),
	('Publicis', 'PUB.PA'),
	('Renault', 'RNO.PA'),
	('Safran', 'SAF.PA'),
	('Saint-Gobain', 'SGO.PA'),
	('Sanofi', 'SAN.PA'),
	('Schneider Electric', 'SU.PA'),
	('Société Générale', 'GLE.PA'),
	('Solvay', 'SOLB.BR'),
	('STMicroelectronics', 'STM.PA'),
	('Technip', 'TEC.PA'),
	('Total', 'FP.PA'),
	('Unibail-Rodamco', 'UL.PA'),
	('Vallourec', 'VK.PA'),
	('Veolia Environnement', 'VIE.PA'),
	('Vinci', 'DG.PA'),
	('Vivendi', 'VIV.PA'),
	('Adidas', 'ADS.DE'),
	('Allianz', 'ALV.DE'),
	('BASF', 'BAS.DE'),
	('Bayer', 'BAYN.DE'),
	('Beiersdorf', 'BEI.DE'),
	('BMW', 'BMW.DE'),
	('Commerzbank', 'CBK.DE'),
	('Daimler', 'DAI.DE'),
	('Deutsche Bank', 'DBK.DE'),
	('Deutsche Börse', 'DB1.DE'),
	('Deutsche Lufthansa', 'LHA.DE'),
	('Deutsche Post', 'DPW.DE'),
	('Deutsche Telekom', 'DTE.DE'),
	('E.ON', 'EOAN.DE'),
	('Fresenius', 'FRE.DE'),
	('Fresenius Medical Care', 'FME.DE'),
	('HeidelbergCement', 'HEI.DE'),
	('Henkel', 'HEN3.DE'),
	('Infineon Technologies', 'IFX.DE'),
	('K+S', 'SDF.DE'),
	('Linde', 'LIN.DE'),
	('MAN', 'MAN.DE'),
	('Merck', 'MRK.DE'),
	('Metro', 'MEO.DE'),
	('Munich Re', 'MUV2.DE'),
	('RWE', 'RWE.DE'),
	('SAP', 'SAP.DE'),
	('Siemens', 'SIE.DE'),
	('ThyssenKrupp', 'TKA.DE'),
	('Volkswagen Group', 'VOW3.DE'),
	('GOOGLE Inc.', 'GOOG'),
	('Activision Blizzard, Inc.', 'ATVI'),
	('ACTIVISION BLIZZARD', 'ATVI'),
	('ADOBE SYSTEMS INC', 'ADBE'),
	('AKAMAI TECHNOLOGIES', 'AKAM'),
	('ALEXION PHARM INC', 'ALXN'),
	('ALTERA CORP', 'ALTR'),
	('AMAZON.COM INC', 'AMZN'),
	('AMGEN', 'AMGN'),
	('ANALOG DEVICES CMN', 'ADI'),
	('APPLE INC', 'AAPL'),
	('APPLIED MATERIALS', 'AMAT'),
	('AUTODESK INC', 'ADSK'),
	('AUTOMATIC DATA PROCS', 'ADP'),
	('AVAGO TECHNOLOGIES L', 'AVGO'),
	('BAIDU, INC.', 'BIDU'),
	('BED BATH & BEYOND', 'BBBY'),
	('BIOGEN IDEC INC', 'BIIB'),
	('BMC SOFTWARE INC', 'BMC'),
	('BROADCOM CORP', 'BRCM'),
	('C.H. ROBINSON WW', 'CHRW'),
	('CA INC', 'CA'),
	('CATAMARAN CORPORATIO', 'CTRX'),
	('CELGENE CORP', 'CELG'),
	('CERNER CORP', 'CERN'),
	('CHECK POINT SOFTWARE', 'CHKP'),
	('CISCO SYSTEMS INC', 'CSCO'),
	('CITRIX SYSTEMS INC', 'CTXS'),
	('COGNIZANT TECH SOL', 'CTSH'),
	('COMCAST CORP A', 'CMCSA'),
	('COSTCO WHOLESALE', 'COST'),
	('DELL INC', 'DELL'),
	('DENTSPLY INTL INC', 'XRAY'),
	('DIRECTV', 'DTV'),
	('DISCOVERY COMM A', 'DISCA'),
	('DOLLAR TREE INC', 'DLTR'),
	('EBAY INC.', 'EBAY'),
	('EQUINIX, INC.', 'EQIX'),
	('EXPEDIA, INC. NEW', 'EXPE'),
	('EXPEDITORS INTL', 'EXPD'),
	('EXPRESS SCRIPTS', 'ESRX'),
	('F5 NETWORKS, INC.', 'FFIV'),
	('FACEBOOK INC', 'FB'),
	('FASTENAL CO', 'FAST'),
	('FISERV, INC.', 'FISV'),
	('FOSSIL INC', 'FOSL'),
	('GARMIN LTD', 'GRMN'),
	('GILEAD SCIENCES, INC', 'GILD'),
	('GOOGLE INC.', 'GOOG'),
	('HENRY SCHEIN, INC.', 'HSIC'),
	('INTEL CORP', 'INTC'),
	('INTUIT INC', 'INTU'),
	('INTUITIVE SURG, INC.', 'ISRG'),
	('K L A-TENCOR CORP', 'KLAC'),
	('LIBERTY GLOBAL CL-A', 'LBTYA'),
	('LIBERTY INTATV SRS A', 'LINTA'),
	('LIBERTY MEDIA CORP A', 'LMCA'),
	('LIFE TECHNOLOGIES', 'LIFE'),
	('LINEAR TECHNOLOGY', 'LLTC'),
	('MATTEL INC', 'MAT'),
	('MAXIM INTEGRATED', 'MXIM'),
	('MICROCHIP TECHNOLOGY', 'MCHP'),
	('MICRON TECHNOLOGY', 'MU'),
	('MICROSOFT CORP', 'MSFT'),
	('MONDELEZ INTL CMN A', 'MDLZ'),
	('MONSTER BEVERAGE CP', 'MNST'),
	('MYLAN INC', 'MYL'),
	('NETAPP, INC.', 'NTAP'),
	('NEWS CORP CL A', 'NWSA'),
	('NUANCE COMMUNICATNS', 'NUAN'),
	('NVIDIA CORPORATION', 'NVDA'),
	('O\'REILLY AUTOMOTIVE', 'ORLY'),
	('ORACLE CORPORATION', 'ORCL'),
	('PACCAR INC.', 'PCAR'),
	('PAYCHEX, INC.', 'PAYX'),
	('PERRIGO COMPANY', 'PRGO'),
	('PRICELINE.COM INC', 'PCLN'),
	('QUALCOMM INC', 'QCOM'),
	('RANDGOLD RES LTD', 'GOLD'),
	('REGENERON PHARMACEUT', 'REGN'),
	('ROSS STORES, INC.', 'ROST'),
	('SANDISK CORPORATION', 'SNDK'),
	('SBA COMMUNICATIONS', 'SBAC'),
	('SEAGATE TECHNOLOGY', 'STX'),
	('SEARS HLDGS CORP', 'SHLD'),
	('SIGMA ALDRICH CORP', 'SIAL'),
	('SIRIUS XM RADIO INC.', 'SIRI'),
	('STAPLES, INC.', 'SPLS'),
	('STARBUCKS CORP', 'SBUX'),
	('STERICYCLE, INC.', 'SRCL'),
	('SYMANTEC CORPORATION', 'SYMC'),
	('TEXAS INSTRUMENTS', 'TXN'),
	('VERISK ANALYTICS INC', 'VRSK'),
	('VERTEX PHARMACEUTIC', 'VRTX'),
	('VIACOM INC CL B', 'VIAB'),
	('VIRGIN MEDIA INC', 'VMED'),
	('VODAFONE GROUP PLC', 'VOD'),
	('WESTERN DIGITAL CP', 'WDC'),
	('WHOLE FOODS MARKET', 'WFM'),
	('WYNN RESORTS LIMITED', 'WYNN'),
	('XILINX, INC.', 'XLNX'),
	('YAHOO! INC.', 'YHOO'),
	('XILINX, INC.', 'XLNX');
/*!40000 ALTER TABLE `STOCK` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
